stages:
  - build
  - deploy

build production on master:
  image: node:10.15.0-stretch
  stage: build
  only:
    - master
  script:
    - npm install yarn
    # Install vuecli
    - yarn global upgrade --latest @vue/cli
    # Install dependencies
    - yarn install
    # Build App
    - yarn build
  artifacts:
    paths:
      # Build folder
      - dist/
    expire_in: 1 hour

deploy prod:
  image: python:latest
  stage: deploy
  only:
    - master
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://online-learning-izteach-3-aws-source-bucket/online-learning-sites/admin

build production on develop:
  image: node:10.15.0-stretch
  stage: build
  only:
    - test
  script:
    - npm install yarn
    # Install vuecli
    - yarn global upgrade --latest @vue/cli
    # Install dependencies
    - yarn install
    # Build App
    - yarn build
  artifacts:
    paths:
      # Build folder
      - dist/
    expire_in: 1 hour

deploy develop:
  image: python:latest
  stage: deploy
  only:
    - test
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://hosting-online-learning-admin-dev
